# Generated by Django 4.2.7 on 2023-12-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('D', 'Deal of the week'), ('F', 'Flash Sale')], max_length=1)),
                ('event_time', models.DateTimeField()),
            ],
        ),
    ]
