# Generated by Django 4.2.7 on 2023-12-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qunatity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
