# Generated by Django 4.2.7 on 2023-12-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_qunatity_cart_quantity_remove_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
